#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Teppei Taguchi"
email = "tetzng.tt@gmail.com"

[ui]
editor = "nvim"

[signing]
behavior = "own"
backend = "gpg"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
